# -*- coding: utf-8 -*-
"""Kdm-lab3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/SAICHANDUALURI/KDM-ICP-3/blob/main/Kdm_lab3.ipynb
"""

import nltk
nltk.download('all')
from nltk.corpus import wordnet

syn = wordnet.synsets('hello')[0] 
print ("\nSynset abstract term :  ", syn.hypernyms()) 
  
print ("\nSynset specific term :  ",  
       syn.hypernyms()[0].hyponyms())
syn = wordnet.synsets('dwelling')[0] 
print ("\nMeronyms :  ", syn.part_meronyms())
syn = wordnet.synsets('tree')[0] 
print ("\nHolonyms :  ", syn.part_holonyms())
syn = wordnet.synsets('eat')[0] 
print ("\nEntailments :  ", syn.entailments())